language: node_js
node_js:
  - "8.9.4"

before_install:
  - npm i -g npm@5.6.0

jobs:
  include:
    - stage: Build and Test
      script: npm run build-ci
      script: npm run test && npm run verify-coverage
    - stage: release
      node_js: lts/*
      # Advanced: optionally overwrite your default `script` step to skip the tests
      # script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release

