language: node_js
node_js:
  - "8.9.4"

before_install:
  - npm i -g npm@latest

jobs:
  include:
    - stage: Build and Test
      script:
        - npm run build-ci
        - npm run test
        - npm run verify-coverage
    - stage: release
      node_js: lts/*
      # Advanced: optionally overwrite your default `script` step to skip the tests
      script:
        - npm run build-ci