language: node_js
node_js:
  - "8.9.4"

before_install:
  - npm i -g npm@5.6.0

jobs:
  include:
    - stage: Build and Test
      script: npm run build-ci
      script: npm run test && npm run verify-coverage
    - stage: Release

